apiVersion: 1
datasources:
  - name: Asset Database
    type: postgres
    url: assetdb:5432
    user: ${AMASS_USER}
    secureJsonData:
      password: ${AMASS_PASSWORD}
    jsonData:
      database: ${AMASS_DB}
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1000
      timescaledb: false
  - name: IP2Location
    type: postgres
    url: assetdb:5432
    user: ${AMASS_USER}
    secureJsonData:
      password: ${AMASS_PASSWORD}
    jsonData:
      database: 'ip2location'
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1000
      timescaledb: false
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "tenant1"
